import { v4 as uuidv4 } from 'uuid';

export const abstractArticles = [
  {
    id: uuidv4(),
    link: '/televisores/mejores-smart-tv-65', 
    linkTitle: 'Encuentra tu Smart TV 65 ideal en el 2023', 
    img: '/archivo/LG_4K_Curved_OLED_TV.jpg', 
    imgTitle: 'Encuentra tu Smart TV 65 ideal en el 2023', 
    imgAlt: 'Imágen Encuentra tu Smart TV 65 ideal en el 2023', 
    title: 'Encuentra tu Smart TV 65 ideal en el 2023', 
    description: 'Descubre las opciones más destacadas de Smart TV de 65" en el 2023 y disfruta de una experiencia de visualización incomparable con lo último en tecnología y calidad de imagen.',
  },
  {
    id: uuidv4(),
    link: '/televisores/smartv-menos-500', 
    linkTitle: 'Ver las mejores TV por menos de 500 euros', 
    img: '/archivo/fondo_smart.jpg', 
    imgTitle: 'Las mejores TV por menos de 500 euros', 
    imgAlt: 'Imágen Las mejores TV por menos de 500 euros', 
    title: 'Las mejores TV por menos de 500 euros - Guía de compra actualizada.', 
    description: 'Descubre las mejores opciones de televisores por menos de 500 euros en el mercado. Conoce las características clave a buscar y elige el televisor perfecto para ti. Guía de compra actualizada y detallada.',
  },
  {
    id: uuidv4(),
    link: '/sonido/sony-ht-a3000', 
    linkTitle: 'Ver guía completa de la barra de Sonido Sony HT-A3000', 
    img: '/sonido/sony/sony_ht-a3000-4.jpg', 
    imgTitle: 'Guía completa para la barra de Sonido Sony HT-A3000', 
    imgAlt: 'Imágen barra de Sonido Sony HT-A3000', 
    title: 'Barra de Sonido Sony HT-A3000: Una experiencia de sonido de cine en casa', 
    description: 'Con la Barra de Sonido Sony HT-A3000, disfruta de una calidad de sonido excepcional en tu cine en casa. Descubre cómo esta barra de sonido puede mejorar tu experiencia de cine en casa.',
  },
  {
    id: uuidv4(),
    link: '/televisores/guia-comprar-smart-tv', 
    linkTitle: 'Ver guía completa para comprar la mejor Smart TV en 2023', 
    img: '/archivo/fondo_comprar_smart.jpg', 
    imgTitle: 'Guía completa para comprar la mejor Smart TV en 2023', 
    imgAlt: 'Imágen Guía completa de compra para comprar la mejor Smart TV en 2023', 
    title: 'Guía completa para comprar la mejor Smart TV en 2023', 
    description: 'Como expertos en tecnología, sabemos que elegir la televisión adecuada es crucial para tener una experiencia de visualización perfecta. Con la llegada del 2023, se espera que el mercado de Smart TVs siga creciendo, y por lo tanto, es importante que conozcas los consejos para comprar la Smart TV adecuada para ti.',
  },
  {
    id: uuidv4(),
    link: '/televisores/mejor-televisor-videojuegos', 
    linkTitle: 'Ver las mejores smart tv para consolas', 
    img: '/archivo/pexels-evg-kowalievska-1174746.jpg', 
    imgTitle: 'Las mejores smart tv para consolas', 
    imgAlt: 'Imágen de pareja jugando en la televisión', 
    title: 'Cómo elegir el mejor televisor para videojuegos', 
    description: '¿Quieres mejorar tu experiencia de juego? Descubre en nuestra guía cómo elegir el mejor televisor para videojuegos. Aprende sobre resolución, frecuencia de actualización, tiempo de respuesta y otras características importantes para disfrutar de juegos con calidad de imagen y sonido excepcional.',
  },
  {
    id: uuidv4(),
    link: '/televisores/cinco-mejores-oled-55', 
    linkTitle: 'Ver mejores las 5 mejores TV OLED de 55 pulgadas', 
    img: '/archivo/pexels-max-rahubovskiy-5998135.jpg', 
    imgTitle: 'Las 5 mejores TV OLED de 55 pulgadas', 
    imgAlt: 'Imágen de las 5 mejores TV OLED de 55 pulgadas', 
    title: 'Las 5 mejores TV OLED de 55 pulgadas calidad-precio', 
    description: 'Descubre las 5 mejores opciones de televisores OLED de 55 pulgadas en el rango medio de precio. Compara las características y precios de los modelos más populares del mercado. Encuentra el televisor perfecto para disfrutar de una calidad de imagen excepcional en tu hogar.',
  },
  {
    id: uuidv4(),
    link: '/televisores/mejores-televisores-2023', 
    linkTitle: 'Ver mejores televisores del 2023', 
    img: '/archivo/pexels-jeshootscom-1040160.jpg', 
    imgTitle: 'Los mejores televisores del 2023', 
    imgAlt: 'Imágen de los mejores televisores del 2023', 
    title: 'Las mejores televisiones de 2023 - Comparativa y guía de compra', 
    description: 'Encuentra la mejor televisión para ti en 2023 con nuestra comparativa y guía de compra. Analizamos las características de las principales marcas y modelos para que puedas tomar una decisión informada. ¡No pierdas más tiempo buscando, encuentra tu televisión ideal aquí!',
  },
  {
    id: uuidv4(),
    link: '/televisores/las-cinco-mejores-marcas', 
    linkTitle: 'Ver mejores marcas del 2023', 
    img: '/pexels-cottonbro-studio-4009409.jpg', 
    imgTitle: 'Las mejores marcas del 2023', 
    imgAlt: 'Imágen de las mejores marcas del 2023', 
    title: 'Las 5 mejores marcas de televisores del mercado en 2023', 
    description: 'Descubre cuáles son las 5 mejores marcas de televisores del mercado en 2023 y por qué debes considerarlas antes de realizar tu próxima compra.',
  },
]