import { v4 as uuidv4 } from 'uuid';

export const mejoresOled = [
  {
    id: uuidv4(),
    img: '/55-oled/lg_oled.png',
    imgAlt: 'Imágen de la LG OLED55C24LA',
    imgTitle: 'LG OLED55C24LA',
    texts: [
        'LG - Televisor 55 pulgadas (139 cm) 4K OLED evo, LG Smart TV webOS22, TV OLED, Procesador Inteligente 4K a9 Gen 5 IA, Compatible con HDR, HDR Dolby Vision y Dolby Atmos, TV para Gaming, OLED55C24LA [Clase de eficiencia energética G]',
    ],
    value: 5,
    reviews: 163,
    link: 'https://amzn.to/3ZzuISI',
    linkTitle: 'Ver en Amazon LG OLED55C24LA',
  },
  {
    id: uuidv4(),
    img: '/55-oled/sony_oled.png',
    imgAlt: 'Imágen de la Sony BRAVIA XR 55A75K',
    imgTitle: 'Sony BRAVIA XR 55A75K',
    texts: [
        'Sony - TV OLED 55" BRAVIA XR 55A75K, 4K HDR 120, HDMI 2.1 óptimo para PS5, Smart TV (Google), Acoustic Surface Audio+, Dolby Vision y Atmos, Triluminos Pro [Clase de eficiencia energética G]',
    ],
    value: 5,
    reviews: 129,
    link: 'https://amzn.to/3ZgJJcs',
    linkTitle: 'Ver en Amazon el Sony BRAVIA XR 55A75K',
  },
  {
    id: uuidv4(),
    img: '/55-oled/samsung_oled.png',
    imgAlt: 'Imágen de la Samsung OLED 55S95',
    imgTitle: 'Samsung OLED 55S95',
    texts: [
        'SAMSUNG TV OLED 55S95 2022 - Smart TV de 55", Tecnología OLED Quantum HDR 1500, Procesador Quantum 4K con Inteligencia Artificial, 60W 60W con Dolby Atmos®, Pantalla Antirreflejos y Alexa integrada [Clase de eficiencia energética G]',
    ],
    value: 5,
    reviews: 12,
    link: 'https://amzn.to/3ZyM9CZ',
    linkTitle: 'Ver en Amazon el Samsung OLED 55S95',
  },
  {
    id: uuidv4(),
    img: '/55-oled/philips_oled.png',
    imgAlt: 'Imágen de la Philips 55OLED807/12',
    imgTitle: 'Philips 55OLED807/12',
    texts: [
        'Philips 55OLED807/12 OLED Android TV 55" 4K UHD, Smart TV con Ambilight Plus de 4 Lados, Dolby Vision cinematográfico y Sonido Atmos, Compatible con Google Assistant y Alexa, 2022 [Clase de eficiencia energética G]',
    ],
    value: 4,
    reviews: 188,
    link: 'https://amzn.to/3Y8R3Fz',
    linkTitle: 'Ver en Amazon el Philips 55OLED807/12',
  },
  {
    id: uuidv4(),
    img: '/55-oled/panasonic_oled.png',
    imgAlt: 'Imágen de la Panasonic TX-55LZ800E',
    imgTitle: 'Panasonic TX-55LZ800E',
    texts: [
        'Panasonic TX-55LZ800E, Televisor OLED 4K 55 Pulgadas, Alto Rango Dinámico (HDR), Cinema Surround, Dolby Atmos y Dolby Vision, Procesador HCX Pro AI, Google Assistant [Clase de eficiencia energética G]',
    ],
    value: 5,
    reviews: 19,
    link: 'https://amzn.to/3ZfD1U1',
    linkTitle: 'Ver en Amazon el Panasonic TX-55LZ800E',
  },
]

export const mejoresVideojuegos = [
  {
    id: uuidv4(),
    img: '/tvs/samsung_55Q64B.png',
    imgAlt: 'Imágen del Samsung TV QLED 4K 2022 55Q64B',
    imgTitle: 'Samsung TV QLED 4K 2022 55Q64B',
    texts: [
        'Smart TV de 55" con Resolución 4K, 100% Volumen de Color, Procesdor QLED 4K Lite, Quantum HDR10+, Multi View, Modo Juego Panorámico y Alexa integrada',
    ],
    value: 5,
    reviews: 163,
    link: 'https://amzn.to/3J5yjmg',
    linkTitle: 'Ver en Amazon Samsung TV QLED 4K 2022 55Q64B',
  },
  {
    id: uuidv4(),
    img: '/55-oled/lg_oled.png',
    imgAlt: 'Imágen del LG Televisor OLED48C24LA',
    imgTitle: 'LG Televisor OLED48C24LA',
    texts: [
        'LG Televisor OLED48C24LA - Smart TV webOS22 48 pulgadas (121 cm) 4K OLED evo, Procesador Inteligente Potencia 4K a9 Gen 5 IA, compatible formatos HDR, HDR Dolby Vision y Dolby Atmos, TV para Gaming',
    ],
    value: 5,
    reviews: 163,
    link: 'https://amzn.to/3Ya7h1i',
    linkTitle: 'Ver en Amazon LG Televisor OLED48C24LA',
  },
  {
    id: uuidv4(),
    img: '/tvs/samsung_50QN90B.png',
    imgAlt: 'Imágen del Samsung Neo QLED 50QN90B',
    imgTitle: 'Samsung Neo QLED 50QN90B',
    texts: [
        'Samsung Smart TV Neo QLED 4K 2022 50QN90B - Smart TV de 50" con Resolución 4K, Quantum Matrix Technology, Procesador Neo QLED 4K con Inteligencia Artificial, Quantum HDR 2000',
    ],
    value: 5,
    reviews: 192,
    link: 'https://amzn.to/41JkIse',
    linkTitle: 'Ver en Amazon Samsung Neo QLED 50QN90B',
  },
  {
    id: uuidv4(),
    img: '/tvs/sony_X90K.png',
    imgAlt: 'Imágen del Sony BRAVIA XR - 65X90K/P',
    imgTitle: 'Sony BRAVIA XR - 65X90K/P',
    texts: [
        'Sony BRAVIA XR - 65X90K/P televisor inteligente Google, Full Array de 65 pulgadas, 4K/P HDR 120Hz y HDMI 2.1 para PS5, Dolby Vision-Atmos, Pantalla Triluminos Pro',
    ],
    value: 5,
    reviews: 40,
    link: 'https://amzn.to/3Ztuz3u',
    linkTitle: 'Ver en Amazon Sony BRAVIA XR - 65X90K/P',
  },
]

export const mejoresMarcas = [
  {
      id: uuidv4(),
      img: '/samsung_QN95B_Neo_QLED.png',
      imgAlt: 'Imágen de la Samsung QN95B Neo QLED',
      imgTitle: 'Samsung QN95B Neo QLED',
      texts: [
          'Samsung TV Neo QLED4K 2022 65QN95B-Smart TV de65" con Resolución 4K, Quantum Matrix Technology, Procesador Neural 4K con Inteligencia Artificial, Quantum HDR2000, 70W Dolby Atmos y Alexa Integrada.',
      ],
      value: 4,
      reviews: 188,
      link: 'https://amzn.to/41vpmd1',
      linkTitle: 'Ver en Amazon el Samsung QN95B Neo QLED',
  },
  {
      id: uuidv4(),
      img: '/samsung_Crystal_UHD_2022.png',
      imgAlt: 'Imágen de la Samsung Crystal UHD 2022 55AU7095',
      imgTitle: 'Samsung Crystal UHD 2022 55AU7095',
      texts: [
          'Samsung Crystal UHD 2022 55AU7095 - Smart TV de 55", 4K UHD, HDR 10, Procesador Crystal 4K, Q-Symphony, Sonido Inteligente y Compatible con Alexa.',
      ],
      value: 5,
      reviews: 3.299,
      link: 'https://amzn.to/41ogRAB',
      linkTitle: 'Ver en Amazon el Samsung Crystal UHD 2022 43AU7095',
  },
  {
      id: uuidv4(),
      img: '/LG_OLED65G26LA.png',
      imgAlt: 'Imágen de la LG OLED65G26LA',
      imgTitle: 'LG OLED65G26LA',
      texts: [
          'LG Televisor OLED65G26LA - Smart TV webOS22 65 pulgadas (164 cm) 4K OLED evo Gallery Edition, Procesador Inteligente 4K a9 Gen 5 IA, compatible formatos HDR, HDR Dolby Vision, Dolby Atmos, TV Gaming.',
      ],
      value: 5,
      reviews: 161,
      link: 'https://amzn.to/3xThzYW',
      linkTitle: 'Ver en Amazon el LG OLED65G26LA',
  },
  {
      id: uuidv4(),
      img: '/LG_OLED55A26LA.png',
      imgAlt: 'Imágen de la LG OLED55A26LA',
      imgTitle: 'LG OLED55A26LA',
      texts: [
          'LG Televisor OLED55A26LA - Smart TV webOS22 55 pulgadas (139 cm) 4K OLED, Procesador Inteligente Gran Potencia 4K a7 Gen 5 IA, compatible formatos HDR, HDR Dolby Vision y Dolby Atmos, TV para Gaming',
      ],
      value: 5,
      reviews: 161,
      link: 'https://amzn.to/41pUUBf',
      linkTitle: 'Ver en Amazon el LG OLED55A26LA',
  },
  {
      id: uuidv4(),
      img: '/Sony_55A95K.png',
      imgAlt: 'Imágen de la Sony QD-OLED 55A95K/P',
      imgTitle: 'Sony QD-OLED 55A95K/P',
      texts: [
          'Sony QD-OLED Master Series - 55A95K/P BRAVIA XR televisor inteligente Google, 4K/P Ultra-HD, para PS5, Bravia CAM incluída, Dolby Vision-Atmos, Pantalla Triluminos MAX.',
      ],
      value: 5,
      reviews: 43,
      link: 'https://amzn.to/3kEeo4n',
      linkTitle: 'Ver en Amazon el Sony QD-OLED 55A95K/P',
  },
  {
      id: uuidv4(),
      img: '/Philips_65OLED706.png',
      imgAlt: 'Imágen de la Philips 65OLED706/12',
      imgTitle: 'Philips 65OLED706/12',
      texts: [
          'Philips 65OLED706/12 4K UHD OLED Android TV, 65 Pulgadas 4K Smart TV con Ambilight, Imagen Vibrante HDR, Dolby Vision cinematográfico y Sonido Atmos, Compatible con Google Assistant y Alexa, 2021.',
      ],
      value: 5,
      reviews: 132,
      link: 'https://amzn.to/3KGA7Dq',
      linkTitle: 'Ver en Amazon el Philips 65OLED706/12',
  },
  {
      id: uuidv4(),
      img: '/Panasonic_TX-65JX800.png',
      imgAlt: 'Imágen de la Panasonic TX-65JX800',
      imgTitle: 'Panasonic TX-65JX800',
      texts: [
          'Panasonic TX-65JX800 Android TV LED 4K HDR 65", Dolby Atmos, HCX, Dolby Vision, Compatible con Amazon Alex y Asistente de Google, HDMI, USB, WiFi, Negro',
      ],
      value: 4,
      reviews: 68,
      link: 'https://amzn.to/3IFea4S',
      linkTitle: 'Ver en Amazon el Panasonic TX-65JX800',
  },
]

export const compraSmart = [
  {
      id: uuidv4(),
      img: '/tvs/philips_50PUS8517.jpg',
      imgAlt: 'Imágen de la Philips 50PUS8517/12',
      imgTitle: 'Philips 50PUS8517/12',
      texts: [
          '<strong>Philips 50PUS8517/12</strong>',
          'TV LED Android TV 4K UHD 50" con Ambilight en 3 Lados, Principales formatos HDR compatibles, P5 Picture Engine, Compatible con Google Assistance y Alexa, 2022.',
      ],
      value: 5,
      reviews: 1.609,
      link: 'https://amzn.to/41GTO43',
      linkTitle: 'Ver en Amazon el Philips 50PUS8517/12',
  },
  {
      id: uuidv4(),
      img: '/tvs/TCL_55P639.jpg',
      imgAlt: 'Imágen de la TCL 55P639',
      imgTitle: 'TCL 55P639',
      texts: [
        '<strong>TCL 55P639</strong>',
        'Smart TV 55" con 4K HDR, Ultra HD, Google TV, Game Master, Dolby Audio, Google Assistant Incorporado & Compatible con Alexa, Metalizado Oscuro.',
      ],
      value: 4,
      reviews: 2.086,
      link: 'https://amzn.to/3kLJTtq',
      linkTitle: 'Ver en Amazon el TCL 55P639',
  },
  {
      id: uuidv4(),
      img: '/tvs/Samsung_55TU8005.jpg',
      imgAlt: 'Imágen de la Samsung UHD 2020 55TU8005',
      imgTitle: 'Samsung UHD 2020 55TU8005',
      texts: [
        '<strong>Samsung UHD 2020 55TU8005</strong>',
        'Smart TV de 55" 4K, HDR 10+, Crystal Display, Procesador 4K, PurColor, Sonido Inteligente, One Remote Control y Asistentes de Voz Integrados, con Alexa integrada.',
      ],
      value: 5,
      reviews: 2.502,
      link: 'https://amzn.to/3kLqAAu',
      linkTitle: 'Ver en Amazon el Samsung UHD 2020 55TU8005',
  },
  {
      id: uuidv4(),
      img: '/tvs/Philips_50PUS8057.jpg',
      imgAlt: 'Imágen de la Philips 50PUS8057/12',
      imgTitle: 'Philips 50PUS8057/12',
      texts: [
        '<strong>Philips 50PUS8057/12</strong>',
        'Smart TV LED 4K UHD AndroidTV de 50", Alto Rango Dinámico (HDR), Dolby Atmos, Imagen y Sonido Cinemáticos, Diseño Delgado, 60 Hz, Ambilight de 3 Lados, Asistente de Google, 2022.',
      ],
      value: 5,
      reviews: 1.514,
      link: 'https://amzn.to/3SONvHF',
      linkTitle: 'Ver en Amazon el Philips 50PUS8057/12',
  },
]