import { v4 as uuidv4 } from 'uuid';

export default function handler(req, res) {
    res.status(200).json([
      {
        id: uuidv4(),
        pos: 10,
        name: 'Xiaomi smart TV P1',
        link: 'https://www.amazon.es/Xiaomi-Smart-Android-Triple-Bluetooth/dp/B0B25VBY7V/ref=sr_1_1?__mk_es_ES=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=3FUSGZU7MTACM&keywords=Xiaomi+smart+TV+P1&qid=1677171084&sprefix=xiaomi+smart+tv+p1%2Caps%2C107&sr=8-1',
        linkTitle: 'Ver en Amazon Xiaomi smart TV P1',
        image: '/71jaCqy3OyL._AC_SL1500_.jpg',
        imageAlt: 'Imágen del televisor Xiaomi smart TV P1',
        features: {
          panel: 'VA Direct LED',
          size: '32″',
          resolution: 'HD / 1366 x 768 píxeles',
          os: 'Android 9, 1.5 GB RAM / 8 GB ROM',
        },
        text: [
          'El Smart TV P1 de Xiaomi es la última incorporación a la gama de televisores de la marca china, y aunque es el modelo más básico, cuenta con prestaciones que satisfarán a los usuarios más exigentes. Es ideal para ser utilizado como televisor secundario, ya que es perfecto para ver programas en una habitación, despacho o cocina. Sin embargo, puede quedarse corto si se utiliza como televisor principal.',
          'Lo que más llama la atención de este televisor es su diseño estilizado y minimalista, con un borde prácticamente invisible que lo hace muy atractivo visualmente. La resolución HD de su panel LCD es adecuada para su tamaño, pero sus altavoces de 5W cada uno pueden quedarse cortos si se busca un sonido potente.',
          'El Smart TV P1 utiliza el sistema operativo Android TV, que es muy completo y fluido, y cuenta con las principales aplicaciones de streaming. Además, viene equipado con Google Assistant y Chromecast, lo que permite la reproducción de contenido desde el móvil y controlarlo mediante comandos de voz.',
          'Disponible en varios tamaños, el Smart TV P1 de Xiaomi es una buena opción para aquellos que buscan un televisor con prestaciones básicas pero de calidad y con un diseño atractivo. Para los que quieren algo más completo y ambicioso para su salón, los modelos de 43, 50 y 55 pulgadas de la gama Xiaomi Smart P1 4K son más recomendables.',
        ],
        pros: [
          'Android TV como sistema operativo',
          'Diseño cuidado',
          'Buena relación calidad precio',
        ],
        con: [
          'Es pequeña para el salón',
          'Propuesta sonora muy básica',
        ],
        stars: 4,
        rating: 107,
        shortDesc: 'El Xiaomi TV P1E 32 es un hub inteligente y rentable que ofrece una experiencia cinematográfica impresionante, con audio y visuales de alta calidad y tecnología Dolby AudioTM y DTSHD Dual Decoder.',
        price: 199,
        decimal: 90,
      },
      {
        id: uuidv4(),
        pos: 9,
        name: 'LG 50UQ70006LB',
        link: 'https://www.amazon.es/Televisor-LG-50UQ70006LB-Procesador-compatible/dp/B09ZV53KKV?pd_rd_w=lWJst&content-id=amzn1.sym.bf9d2b27-0fc0-4063-b270-4bd5cf1225a1&pf_rd_p=bf9d2b27-0fc0-4063-b270-4bd5cf1225a1&pf_rd_r=5QC9WH67NYSJHHA5WP09&pd_rd_wg=LTX2x&pd_rd_r=bed52915-3203-4bb1-919d-5abb4fae2157&pd_rd_i=B09ZV53KKV&psc=1&linkCode=sl1&tag=smartstvs-21&linkId=5444c53bc4176f2a78b589b2df298d9c&language=es_ES&ref_=as_li_ss_tl',
        linkTitle: 'Ver en Amazon LG 50UQ70006LB',
        image: '/91+uC0bwmNL._AC_SX679_.jpg',
        imageAlt: 'Imágen del televisor LG 50UQ70006LB',
        features: {
          panel: 'VA Direct LED',
          size: '50″',
          resolution: '4K',
          os: 'WebOS 22',
        },
        text: [
          'Si estás buscando una televisión inteligente de calidad sin gastar demasiado, el LG 50UQ70006LB es una excelente opción. Este modelo ofrece una resolución 4K y un sistema operativo fluido, lo que te permitirá disfrutar de una experiencia de visualización óptima. Aunque su diseño es algo simple, si la estética no es tu prioridad o quieres que pase desapercibido en tu sala de estar, esto no será un problema.',
          'En cuanto a la pantalla, destaca por su excelente brillo, contraste y fidelidad en la reproducción del color, lo que es propio de gamas más altas. Además, la resolución 4K te permitirá disfrutar de un gran nivel de detalle en series, películas y programas en directo, especialmente en contenidos HDR10 y HLG. Ten en cuenta que para aprovechar al máximo las cualidades de su panel, es importante que te sientes enfrente de la televisión, ya que puede perder un poco de calidad de imagen si te sientas a un lado.',
          'Si eres un amante del cine en casa, te encantará el sistema de sonido de 20W con Ultra Surround de 5.1 canales compatible con Dolby Digital. Y si te gusta ver contenido en plataformas como Netflix o Prime Video, el sistema operativo WebOS es muy intuitivo y fácil de usar, lo que te permitirá navegar sin problemas. Además, si quieres controlar tu televisor con altavoces inteligentes de Amazon o Google, estos son compatibles.',
          'En cuanto al gaming, aunque este televisor tiene una buena calidad de pantalla y baja latencia, no cuenta con las últimas tecnologías específicas para juegos como los puertos HDMI 2.1. Por lo tanto, si eres un jugador intensivo o te gustan los triple A, es posible que este televisor no sea la mejor opción.',
          'En resumen, si buscas una televisión inteligente de calidad a un precio asequible, el LG 50UQ70006LB es una gran opción que puedes encontrar en diferentes tamaños (43, 50 y 55 pulgadas) para adaptarse a tus preferencias de tamaño de pantalla.',
          
        ],
        pros: [
          'Sonido sorprendente para su precio',
          'Sistema operativo fluido e intuitivo',
          'Buena calidad de imagen',
        ],
        con: [
          'Diseño sencillo',
          'Sin tecnologías para jugar',
          'Cuidado con el ángulo de visión',
        ],
        stars: 4.5,
        rating: 72,
        shortDesc: 'La Smart TV de LG tiene Inteligencia Artificial y formato HDR. Su procesador 4K a5 Gen 5 ofrece tonos y colores precisos, con sonido Surround 5.1. Compatible con Apple, Google y Alexa, y con funciones Gaming como Cloud Gaming y baja latencia.',
        price: '346',
        decimal: '78',
      },
      {
        id: uuidv4(),
        pos: 8,
        name: 'Sony Bravia XR A75K',
        link: 'https://www.amazon.es/TV-OLED-55-Acoustic-Triluminos/dp/B09ZLH8ZJ6/ref=sr_1_1?__mk_es_ES=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=ATNJEJ2R41FR&keywords=Sony+-+TV+OLED+55%22+BRAVIA+XR+55A75K%2C+4K+HDR+120%2C+HDMI+2.1+%C3%B3ptimo+para+PS5%2C+Smart+TV+%28Google%29%2C+Acoustic+Surface+Audio%2B%2C+Dolby+Vision+y+Atmos%2C+Triluminos+Pro&qid=1677228527&s=electronics&sprefix=sony+-+tv+oled+55%22+bravia+xr+55a75k+4k+hdr+120+hdmi+2.1+%C3%B3ptimo+para+ps5+smart+tv+google+acoustic+surface+audio+dolby+vision+y+atmos+triluminos+pro%2Celectronics%2C89&sr=1-1',
        linkTitle: 'Ver en Amazon Sony Bravia XR A75K',
        image: '/81JFothDFbL._AC_SL1500_.jpg',
        imageAlt: 'Imágen del televisor Sony Bravia XR A75K',
        features: {
          panel: 'OLED',
          size: '55″',
          resolution: '4K',
          os: 'Google TV',
        },
        text: [
          'Sony es una marca icónica en el mundo de los televisores, especialmente en la gama media alta. La Sony Bravia XR A75K es su modelo OLED más modesto para el año 2022, pero es uno de los televisores más interesantes para los amantes del cine.',
          'Este televisor es minimalista y funcional en su estética, con una pantalla que ocupa casi toda la superficie del frontal, marcos muy finos y patas discretas en los laterales. Aunque no sea el más moderno en cuanto a diseño, compensa con creces una vez que se enciende.',
          'La calidad de su panel es impresionante, incluso para los usuarios más exigentes. La experiencia de ver películas en este televisor es realmente similar a la de estar en una sala de cine, gracias a su imagen y sonido de alta calidad.',
          'El panel OLED de 10 bits ofrece colores profundos, nítidos y llamativos, y brilla gracias al efecto de Dolby Vision o HDR10 si el contenido es compatible. La única desventaja es que no es compatible con HDR10+.',
          'El sonido es igual de impresionante, gracias a que es compatible con Dolby Atmos, tiene una potencia de 50W y cuenta con configuración acústica 2.2 con doble subwoofer que refuerza las bajas frecuencias.',
          'Si te gusta ver contenido en streaming, apreciarás la versión simplificada de Android TV llamada Google TV, que es muy fácil de usar. Además, viene con Chromecast integrado para que puedas lanzar contenido directamente desde tu móvil.',
          'Si tienes una consola de última generación o planeas comprar una próximamente, te encantará que este televisor tenga dos puertos HDMI 2.1 y tecnologías que te permitan aprovecharlas al máximo, como el modo automático de baja latencia o la tasa de refresco variable.',
          'Si bien el Sony Bravia XR A75K no es barato, si buscas calidad de imagen y un sonido cuidado tanto para cine como para juegos, este televisor es una excelente opción. Y si necesitas una pantalla aún más grande, también está disponible en 65 pulgadas.',
          
        ],
        pros: [
          'Alta calidad de imagen',
          'Sonido cuidado',
          'Fluidez y sencillez de Google TV',
          'Apto para jugones',
        ],
        con: [
          'Precio elevado',
          'No es compatible con HDR10+',
          'Diseño poco moderno',
        ],
        stars: 4.5,
        rating: 125,
        shortDesc: 'El Sony OLED ofrece colores óptimos y ángulos de visión superiores, con sonido envolvente y un diseño inmersivo. Óptimo para juegos y consolas, con baja latencia y VRR. Control por voz y acceso a 700k películas y episodios de TV con Google TV.',
        price: '1.499',
        decimal: '00',
      },
      {
        id: uuidv4(),
        pos: 7,
        name: 'Sony XR90J',
        link: 'https://www.amazon.es/SONY-XR55X90J-TRIL-F-Array-BRAVI/dp/B097YBSKRB/ref=sr_1_1?__mk_es_ES=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=1EXU00K7Q68JC&keywords=Sony+XR90J&qid=1677229536&s=electronics&sprefix=sony+xr90j%2Celectronics%2C86&sr=1-1',
        linkTitle: 'Ver en Amazon Sony XR90J',
        image: '/Sony-XR90J.jpg',
        imageAlt: 'Imágen del televisor Sony XR90J',
        features: {
          panel: 'LCD VA FALD',
          size: '55″',
          resolution: '4K',
          os: 'Android TV',
        },
        text: [
          'Si no te importa que el modelo no sea de este año, Sony tiene en su cartera de televisores un modelo de gama alta todoterreno por debajo de los mil euros que es un verdadero as en la manga: el Sony XR90J. Este televisor es una excelente opción tanto para los amantes de los juegos como para los aficionados al cine y las series.',
          'Lo que más nos gusta de su panel es su excelente brillo y la precisión del color, dos características que se aprecian especialmente cuando se pasa mucho tiempo frente al televisor. Se nota que es de gama alta gracias a la calidad de su panel: un ambicioso LCD con retroiluminación Full Array Local Dimming. Además, es compatible con los principales estándares HDR, lo que significa que podrás reproducir en él contenido con una calidad extra.',
          'Este televisor también tiene una durabilidad superior a la de los modelos OLED, lo cual es ideal si tienes la televisión encendida todo el día, ya que no tendrás que preocuparte por zonas quemadas con el paso del tiempo. Sin embargo, aunque el Dolby Vision logra un efecto sonoro espacial convincente, los altavoces podrían ser más potentes.',
          'Si eres un cinéfilo o un seriéfilo, Android TV tiene una gran cantidad de aplicaciones y funciona de manera excelente. Si quieres más, puedes reproducir el contenido desde tu móvil con el Chromecast integrado.',
          "Si tienes una PS5 o una Xbox X, estás de suerte: la experiencia con títulos como Assassin's Creed es de altísimo nivel gracias a la fluidez y el nivel de detalle que proporcionan tecnologías como HDMI 2.1, la tasa de frecuencia variable y su baja latencia.",
          'Sony suele cuidar la estética de sus productos y este Sony XR90J no es una excepción: su diseño es estilizado y atractivo a la vista, con unos acabados de primera.',
          'Lo que menos nos ha gustado de este televisor Sony es su precio, ya que hay otros fabricantes que ofrecen prestaciones similares a precios más ajustados. Sin embargo, es indudable que este modelo cumple las expectativas de quienes buscan una televisión de alta calidad.',
          
        ],
        pros: [
          'Disfrutarás de la calidad de su pantalla',
          'Apta para uso intensivo',
          'Con HDMI 2.1 para jugar',
        ],
        con: [
          'Propuesta sonora mejorable',
          'No es barato para sus prestaciones',
        ],
        stars: 4.5,
        rating: 125,
        shortDesc: 'El televisor Sony XR55X90J UHD TRIL STV XR F.ARRAY BRAVI es un producto de alta calidad de Sony Corporation, una multinacional japonesa que fabrica una amplia gama de productos electrónicos, desde televisores y equipos de sonido hasta cámaras digitales y juegos electrónicos.',
        price: '1.303',
        decimal: '93',
      },
      {
        id: uuidv4(),
        pos: 6,
        name: 'Samsung QLED 2021 55Q75A',
        link: 'https://www.amazon.es/SONY-XR55X90J-TRIL-F-Array-BRAVI/dp/B097YBSKRB/ref=sr_1_1?__mk_es_ES=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=1EXU00K7Q68JC&keywords=Sony+XR90J&qid=1677229536&s=electronics&sprefix=sony+xr90j%2Celectronics%2C86&sr=1-1',
        linkTitle: 'Ver en Amazon Samsung QLED 2021 55Q75A',
        image: '/samsungqled.jpg',
        imageAlt: 'Imágen del televisor Samsung QLED 2021 55Q75A',
        features: {
          panel: 'VA Edge LED',
          size: '55″',
          resolution: '4K',
          os: 'Tizen 6.0',
        },
        text: [
          'Samsung destaca en la gama media con su oferta QLED, que se caracteriza por su elegante diseño y el buen rendimiento de su sistema operativo, sin sacrificar la calidad de imagen. Sin embargo, hay diferencias significativas entre las familias de televisores.',
          'La línea Q75 es especialmente atractiva en términos de calidad-precio, ya que a partir de esta familia todos los modelos cuentan con HDMI 2.1. Es el televisor más asequible de Samsung este año para los jugadores.',
          'Si tienes una consola de última generación, este televisor es ideal. Con HDMI 2.1, su modo automático de baja latencia, tasa de refresco variable, modo para juegos y AMD FreeSync, ofrece una experiencia completa para los jugadores. En cuanto a la calidad de imagen, es buena, especialmente considerando su tamaño. Aunque Samsung llama a su gama alta "QLED", en realidad utiliza paneles VA con diferentes sistemas de retroiluminación, en este caso, Edge LED.',
          'El alto rango dinámico hace que los detalles se aprecien mejor, especialmente en escenas oscuras como las de Juego de Tronos. Aunque este modelo implementa HDR10, HDR10+ y HLG, es inexplicable que por su precio no sea compatible con Dolby Vision. En cuanto a la navegación por aplicaciones como Netflix o Prime Video, el Tizen 6.0 es bastante fluido.',
          "El modelo analizado es de 55 pulgadas, aunque también está disponible en versiones de 65 y 75 pulgadas. Si buscas una experiencia más premium con una mejor reproducción de color y brillo, tendrás que pagar más. En general, Samsung ha logrado un producto equilibrado con este televisor sin aumentar demasiado su precio.",
        ],
        pros: [
          'Diseño estilizado premium',
          'Con las últimas tecnologías para jugar',
          'Buena relación calidad precio',
        ],
        con: [
          'No es compatible con Dolby Vision',
          'Brillo mejorable',
        ],
        stars: 4.5,
        rating: 125,
        shortDesc: 'SAMSUNG QLED 4K 2021 55Q75A - Smart TV de 55" con Resolución 4K UHD, Procesador QLED 4K con IA, Quantum HDR10+, Wide Viewing Angle, Motion Xcelerator Turbo+, OTS Lite y Alexa Integrada.',
        price: '1.099',
        decimal: '00',
      },
    ])
  }