import { v4 as uuidv4 } from 'uuid';

export const tvList = [
  {
    id: uuidv4(),
    pos: 10,
    name: 'Xiaomi P1E Smart TV 32',
    link: 'https://amzn.to/3EBkUzL',
    linkTitle: 'Ver en Amazon Xiaomi P1E Smart TV 32',
    image: '/xiaomi_p1e.png',
    imageAlt: 'Imágen del televisor Xiaomi P1E Smart TV 32',
    features: {
      panel: 'LED',
      size: '32″',
      resolution: '1.366 x 768 pixeles (HD-ready / 720p)',
      os: 'Android TV 11.0',
    },
    text: [
      'El Xiaomi P1E Smart TV de 32 pulgadas es una televisión inteligente de alta calidad y asequible lanzada por la reconocida marca tecnológica Xiaomi. Este televisor cuenta con características avanzadas que lo convierten en una excelente opción para aquellos que buscan un televisor con una buena relación calidad-precio.',
      'La pantalla del Xiaomi P1E Smart TV tiene una resolución de 1366 x 768 píxeles y una tasa de refresco de 60Hz. Esta pantalla utiliza tecnología LED para brindar una excelente calidad de imagen con colores vibrantes y negros profundos. Además, cuenta con un ángulo de visión de 178 grados, lo que significa que la imagen se ve bien desde cualquier ángulo.',
      'El Xiaomi P1E Smart TV viene con el sistema operativo Android TV 9.0, lo que permite a los usuarios acceder a una amplia variedad de aplicaciones y contenido en línea. Los usuarios pueden descargar aplicaciones populares como Netflix, Amazon Prime Video, YouTube, entre otras. Además, cuenta con Google Assistant integrado, lo que permite a los usuarios controlar el televisor por voz.',
      'En cuanto al audio, el Xiaomi P1E Smart TV cuenta con dos altavoces de 5W cada uno, lo que brinda un sonido claro y nítido. También cuenta con tecnología de sonido DTS-HD, que mejora aún más la calidad del audio.',
      'El Xiaomi P1E Smart TV tiene un diseño elegante y minimalista, con un marco delgado y un soporte en forma de "V". También cuenta con puertos HDMI, USB y Ethernet para conectar otros dispositivos y accesorios.',
      'En resumen, el Xiaomi P1E Smart TV de 32 pulgadas es un televisor inteligente con características avanzadas a un precio asequible. Ofrece una excelente calidad de imagen, acceso a una amplia variedad de aplicaciones y contenido en línea, y una calidad de audio impresionante. Es una excelente opción para aquellos que buscan un televisor de alta calidad sin gastar demasiado dinero.',
    ],
    pros: [
      'Pantalla de alta calidad.',
      'Acceso a aplicaciones en línea.',
      'Audio claro y nítido.',
      'Buen precio.',
      'Diseño elegante.',
    ],
    con: [
      'Resolución limitada.',
      'Tasa de refresco baja.',
    ],
    stars: 4,
    rating: 103,
    shortDesc: 'El Xiaomi P1E Smart TV de 32 pulgadas es una televisión inteligente de alta calidad y asequible. Cuenta con una pantalla LED de 1366 x 768 píxeles, acceso a una amplia variedad de aplicaciones y contenido en línea, audio claro y nítido, y un diseño elegante. Sin embargo, la resolución y la tasa de refresco son limitadas.',
    price: 199,
    decimal: 90,
  },
  {
    id: uuidv4(),
    pos: 9,
    name: 'LG Televisor 50UQ75006LF',
    link: 'https://amzn.to/3ISfjaT',
    linkTitle: 'Ver en Amazon LG Televisor 50UQ75006LF',
    image: '/LG_Televisor_50UQ75006LF.png',
    imageAlt: 'Imágen del televisor LG Televisor 50UQ75006LF',
    features: {
      panel: 'LED',
      size: '50″',
      resolution: '4K',
      os: 'ThinQ',
    },
    text: [
      'El LG Televisor 50UQ75006LF es un televisor inteligente de 50 pulgadas con resolución 4K y tecnología de imagen UHD. Este televisor cuenta con una amplia gama de colores y un contraste dinámico que garantiza una calidad de imagen impresionante. Además, cuenta con tecnología HDR para ofrecer imágenes aún más realistas y detalladas.',
      'Este televisor cuenta con un sistema operativo inteligente LG ThinQ AI que te permite controlar tu televisor con tu voz y acceder a una amplia variedad de aplicaciones de streaming como Netflix, Amazon Prime Video y YouTube. También puedes acceder a la galería LG y disfrutar de una amplia variedad de contenido gratuito y de pago.',
      'El LG Televisor 50UQ75006LF también cuenta con conectividad Wi-Fi y Bluetooth, lo que te permite conectarte fácilmente a internet y acceder a tus dispositivos móviles. También cuenta con puertos HDMI y USB, lo que te permite conectar fácilmente tus dispositivos externos, como tu consola de juegos, reproductor de Blu-ray o disco duro externo.',
      'En cuanto al diseño, el LG Televisor 50UQ75006LF presenta un elegante diseño con marcos ultra delgados que maximizan la superficie de visualización y le dan un aspecto moderno y sofisticado. También cuenta con un soporte resistente y estable que se adapta perfectamente a cualquier decoración de interiores.',
      'En resumen, el LG Televisor 50UQ75006LF es un televisor inteligente de alta calidad que ofrece una calidad de imagen impresionante, una amplia variedad de características inteligentes y una conectividad conveniente. Si buscas un televisor de calidad superior para tu hogar, el LG Televisor 50UQ75006LF es una excelente opción.',
    ],
    pros: [
      'Resolución 4K impresionante',
      'Amplia gama de colores',
      'Tecnología HDR para imágenes realistas',
      'Sistema operativo inteligente',
      'Conectividad Wi-Fi y Bluetooth',
    ],
    con: [
      'No incluye soporte giratorio',
      'No cuenta con HDMI 2.1',
      'Precio elevado en comparación a otros modelos',
    ],
    stars: 4.5,
    rating: 54,
    shortDesc: 'El LG Televisor 50UQ75006LF es un televisor inteligente de 50 pulgadas con resolución 4K y tecnología UHD. Cuenta con un sistema operativo inteligente LG ThinQ AI, conectividad Wi-Fi y Bluetooth, y una amplia variedad de aplicaciones de streaming. Su diseño elegante con marcos ultra delgados lo hacen una excelente opción para cualquier hogar.',
    price: '385',
    decimal: '78',
  },
  {
    id: uuidv4(),
    pos: 8,
    name: 'Sony Bravia XR A75K',
    link: 'https://amzn.to/3y8n1aJ',
    linkTitle: 'Ver en Amazon Sony Bravia XR A75K',
    image: '/Sony_Bravia_XR_A75K.png',
    imageAlt: 'Imágen del televisor Sony Bravia XR A75K',
    features: {
      panel: 'OLED',
      size: '55″',
      resolution: '4K',
      os: 'Google TV',
    },
    text: [
      'Sony es una marca icónica en el mundo de los televisores, especialmente en la gama media alta. La Sony Bravia XR A75K es su modelo OLED más modesto para el año 2022, pero es uno de los televisores más interesantes para los amantes del cine.',
      'Este televisor es minimalista y funcional en su estética, con una pantalla que ocupa casi toda la superficie del frontal, marcos muy finos y patas discretas en los laterales. Aunque no sea el más moderno en cuanto a diseño, compensa con creces una vez que se enciende.',
      'La calidad de su panel es impresionante, incluso para los usuarios más exigentes. La experiencia de ver películas en este televisor es realmente similar a la de estar en una sala de cine, gracias a su imagen y sonido de alta calidad.',
      'El panel OLED de 10 bits ofrece colores profundos, nítidos y llamativos, y brilla gracias al efecto de Dolby Vision o HDR10 si el contenido es compatible. La única desventaja es que no es compatible con HDR10+.',
      'El sonido es igual de impresionante, gracias a que es compatible con Dolby Atmos, tiene una potencia de 50W y cuenta con configuración acústica 2.2 con doble subwoofer que refuerza las bajas frecuencias.',
      'Si te gusta ver contenido en streaming, apreciarás la versión simplificada de Android TV llamada Google TV, que es muy fácil de usar. Además, viene con Chromecast integrado para que puedas lanzar contenido directamente desde tu móvil.',
      'Si tienes una consola de última generación o planeas comprar una próximamente, te encantará que este televisor tenga dos puertos HDMI 2.1 y tecnologías que te permitan aprovecharlas al máximo, como el modo automático de baja latencia o la tasa de refresco variable.',
      'Si bien el Sony Bravia XR A75K no es barato, si buscas calidad de imagen y un sonido cuidado tanto para cine como para juegos, este televisor es una excelente opción. Y si necesitas una pantalla aún más grande, también está disponible en 65 pulgadas.',
      
    ],
    pros: [
      'Alta calidad de imagen',
      'Sonido cuidado',
      'Fluidez y sencillez de Google TV',
      'Apto para jugones',
    ],
    con: [
      'Precio elevado',
      'No es compatible con HDR10+',
      'Diseño poco moderno',
    ],
    stars: 4.5,
    rating: 125,
    shortDesc: 'El Sony OLED ofrece colores óptimos y ángulos de visión superiores, con sonido envolvente y un diseño inmersivo. Óptimo para juegos y consolas, con baja latencia y VRR. Control por voz y acceso a 700k películas y episodios de TV con Google TV.',
    price: '1.499',
    decimal: '00',
  },
  {
    id: uuidv4(),
    pos: 7,
    name: 'Sony XR90J',
    link: 'https://amzn.to/3XSluQo',
    linkTitle: 'Ver en Amazon Sony XR90J',
    image: '/Sony_TV_55_XR55X90J.png',
    imageAlt: 'Imágen del televisor Sony XR90J',
    features: {
      panel: 'LCD VA FALD',
      size: '55″',
      resolution: '4K',
      os: 'Android TV',
    },
    text: [
      'Si no te importa que el modelo no sea de este año, Sony tiene en su cartera de televisores un modelo de gama alta todoterreno por debajo de los mil euros que es un verdadero as en la manga: el Sony XR90J. Este televisor es una excelente opción tanto para los amantes de los juegos como para los aficionados al cine y las series.',
      'Lo que más nos gusta de su panel es su excelente brillo y la precisión del color, dos características que se aprecian especialmente cuando se pasa mucho tiempo frente al televisor. Se nota que es de gama alta gracias a la calidad de su panel: un ambicioso LCD con retroiluminación Full Array Local Dimming. Además, es compatible con los principales estándares HDR, lo que significa que podrás reproducir en él contenido con una calidad extra.',
      'Este televisor también tiene una durabilidad superior a la de los modelos OLED, lo cual es ideal si tienes la televisión encendida todo el día, ya que no tendrás que preocuparte por zonas quemadas con el paso del tiempo. Sin embargo, aunque el Dolby Vision logra un efecto sonoro espacial convincente, los altavoces podrían ser más potentes.',
      'Si eres un cinéfilo o un seriéfilo, Android TV tiene una gran cantidad de aplicaciones y funciona de manera excelente. Si quieres más, puedes reproducir el contenido desde tu móvil con el Chromecast integrado.',
      "Si tienes una PS5 o una Xbox X, estás de suerte: la experiencia con títulos como Assassin's Creed es de altísimo nivel gracias a la fluidez y el nivel de detalle que proporcionan tecnologías como HDMI 2.1, la tasa de frecuencia variable y su baja latencia.",
      'Sony suele cuidar la estética de sus productos y este Sony XR90J no es una excepción: su diseño es estilizado y atractivo a la vista, con unos acabados de primera.',
      'Lo que menos nos ha gustado de este televisor Sony es su precio, ya que hay otros fabricantes que ofrecen prestaciones similares a precios más ajustados. Sin embargo, es indudable que este modelo cumple las expectativas de quienes buscan una televisión de alta calidad.',
      
    ],
    pros: [
      'Disfrutarás de la calidad de su pantalla',
      'Apta para uso intensivo',
      'Con HDMI 2.1 para jugar',
    ],
    con: [
      'Propuesta sonora mejorable',
      'No es barato para sus prestaciones',
    ],
    stars: 4.5,
    rating: 12,
    shortDesc: 'El televisor Sony XR55X90J UHD TRIL STV XR F.ARRAY BRAVI es un producto de alta calidad de Sony Corporation, una multinacional japonesa que fabrica una amplia gama de productos electrónicos, desde televisores y equipos de sonido hasta cámaras digitales y juegos electrónicos.',
    price: '1.303',
    decimal: '93',
  },
  {
    id: uuidv4(),
    pos: 6,
    name: 'Samsung TV QLED 4K 2022 55Q64B',
    link: 'https://amzn.to/3IR5J7V',
    linkTitle: 'Ver en Amazon Samsung TV QLED 4K 2022 55Q64B',
    image: '/samsung_qled_55q64.png',
    imageAlt: 'Imágen del televisor Samsung TV QLED 4K 2022 55Q64B',
    features: {
      panel: 'VA Edge LED',
      size: '55″',
      resolution: '4K',
      os: 'Tizen 6.0',
    },
    text: [
      'Samsung destaca en la gama media con su oferta QLED, que se caracteriza por su elegante diseño y el buen rendimiento de su sistema operativo, sin sacrificar la calidad de imagen. Sin embargo, hay diferencias significativas entre las familias de televisores.',
      'La línea Q75 es especialmente atractiva en términos de calidad-precio, ya que a partir de esta familia todos los modelos cuentan con HDMI 2.1. Es el televisor más asequible de Samsung este año para los jugadores.',
      'Si tienes una consola de última generación, este televisor es ideal. Con HDMI 2.1, su modo automático de baja latencia, tasa de refresco variable, modo para juegos y AMD FreeSync, ofrece una experiencia completa para los jugadores. En cuanto a la calidad de imagen, es buena, especialmente considerando su tamaño. Aunque Samsung llama a su gama alta "QLED", en realidad utiliza paneles VA con diferentes sistemas de retroiluminación, en este caso, Edge LED.',
      'El alto rango dinámico hace que los detalles se aprecien mejor, especialmente en escenas oscuras como las de Juego de Tronos. Aunque este modelo implementa HDR10, HDR10+ y HLG, es inexplicable que por su precio no sea compatible con Dolby Vision. En cuanto a la navegación por aplicaciones como Netflix o Prime Video, el Tizen 6.0 es bastante fluido.',
      "El modelo analizado es de 55 pulgadas, aunque también está disponible en versiones de 65 y 75 pulgadas. Si buscas una experiencia más premium con una mejor reproducción de color y brillo, tendrás que pagar más. En general, Samsung ha logrado un producto equilibrado con este televisor sin aumentar demasiado su precio.",
    ],
    pros: [
      'Diseño estilizado premium',
      'Con las últimas tecnologías para jugar',
      'Buena relación calidad precio',
    ],
    con: [
      'No es compatible con Dolby Vision',
      'Brillo mejorable',
    ],
    stars: 4.5,
    rating: 156,
    shortDesc: 'Samsung 2022 55Q75B - Smart TV de 55" con Resolución 4K UHD, Procesador QLED 4K con IA, Quantum HDR10+, Wide Viewing Angle, Motion Xcelerator Turbo+, OTS Lite y Alexa Integrada.',
    price: '1.099',
    decimal: '00',
  },
  {
    id: uuidv4(),
    pos: 5,
    name: 'Samsung TV Crystal UHD 2022 50BU8000',
    link: 'https://amzn.to/3KB6WSb',
    linkTitle: 'Ver en Amazon Samsung TV Crystal UHD 2022 50BU8000',
    image: '/Samsung_Crystal_50BU8000.png',
    imageAlt: 'Imágen del televisor Samsung TV Crystal UHD 2022 50BU8000',
    features: {
      panel: 'VA Edge LED',
      size: '55″',
      resolution: '4K',
      os: 'Tizen 6.0',
    },
    text: [
      'La Samsung TV Crystal UHD 2022 50BU8000 es un televisor de gama media que cuenta con un panel LED de 50 pulgadas con resolución 4K UHD y tecnología de cristal. Esto permite una imagen nítida y clara con colores vibrantes y contrastes profundos.',
      'Este modelo también cuenta con el procesador Crystal 4K de Samsung, que optimiza la calidad de imagen y el rendimiento del televisor. Además, viene equipado con el sistema operativo Tizen de Samsung, que es rápido y fácil de usar para acceder a aplicaciones de streaming como Netflix, Amazon Prime Video, y Disney+.',
      'Otras características notables incluyen el soporte para HDR, lo que permite una mayor profundidad de color y detalles en escenas oscuras, y la tecnología de sonido envolvente que ofrece una experiencia de audio mejorada. Además, la conectividad es amplia, incluyendo cuatro puertos HDMI, dos puertos USB, Wi-Fi integrado y Bluetooth.',
      'En general, la Samsung TV Crystal UHD 2022 50BU8000 es una excelente opción para aquellos que buscan un televisor de alta calidad a un precio asequible, con una buena calidad de imagen y una amplia gama de características y funciones.',
    ],
    pros: [
      'Resolución 4K UHD y tecnología de cristal para una imagen nítida y colores vibrantes.',
      'Procesador Crystal 4K para una mejor calidad de imagen y rendimiento.',
      'Sistema operativo Tizen rápido y fácil de usar para acceder a aplicaciones de streaming.',
      'Soporte para HDR para una mayor profundidad de color y detalles en escenas oscuras.',
      'Conectividad amplia con cuatro puertos HDMI, dos puertos USB, Wi-Fi integrado y Bluetooth.',
    ],
    con: [
      'Diseño y construcción pueden no ser tan elegantes o robustos como modelos de gama alta.',
      'Ángulo de visión limitado que puede afectar la calidad de imagen desde ángulos amplios.',
      "Calidad de sonido puede no ser suficiente para una experiencia de audio inmersiva.",
      "Puede carecer de algunas características avanzadas de modelos de gama alta, como Dolby Vision o tecnología de retroiluminación más avanzada.",
    ],
    stars: 4.5,
    rating: 1.691,
    shortDesc: 'Samsung TV Crystal UHD 2022 50BU8000 ofrece una resolución 4K UHD con tecnología de cristal para una imagen nítida y colores vibrantes. Cuenta con el procesador Crystal 4K y sistema operativo Tizen para una mejor calidad de imagen y experiencia de usuario. Soporte para HDR y conectividad amplia con cuatro puertos HDMI, dos puertos USB, Wi-Fi integrado y Bluetooth. Sin embargo, puede tener un ángulo de visión limitado y carecer de algunas características avanzadas de modelos de gama alta.',
    price: '479',
    decimal: '00',
  },
  {
    id: uuidv4(),
    pos: 4,
    name: 'Hisense 50E76GQ QLED 2021',
    link: 'https://amzn.to/41srceW',
    linkTitle: 'Ver en Amazon Hisense 50E76GQ QLED 2021',
    image: '/Hisense_50E76GQ_QLED_2021.png',
    imageAlt: 'Imágen del televisor Hisense 50E76GQ QLED 2021',
    features: {
      panel: 'QLED',
      size: '55″',
      resolution: '4K',
      os: 'VIDAA U5',
    },
    text: [
      'El Hisense 50E76GQ QLED 2021 es un televisor de gama media con una calidad de imagen impresionante. Este televisor de 50 pulgadas cuenta con una resolución de 4K Ultra HD y tecnología QLED, lo que garantiza una imagen brillante y vibrante con una gran precisión de color. Además, cuenta con un sistema de iluminación trasera Full Array Local Dimming (FALD) que mejora aún más la calidad de la imagen al proporcionar un mayor contraste y profundidad.',
      'El diseño del Hisense 50E76GQ es elegante y minimalista, con un marco delgado que maximiza la pantalla. El televisor también cuenta con una plataforma inteligente que permite acceder fácilmente a una amplia gama de aplicaciones y servicios de streaming como Netflix, Amazon Prime Video y YouTube, entre otros. Además, el control remoto es intuitivo y fácil de usar.',
      'El análisis de este televisor muestra que su rendimiento es impresionante en términos de calidad de imagen, pero también cuenta con características adicionales como una buena conectividad que incluye cuatro puertos HDMI, dos puertos USB y una conexión de red Ethernet. Además, el televisor cuenta con tecnología de sonido Dolby Atmos que proporciona un sonido envolvente y claro.',
      'En resumen, el Hisense 50E76GQ QLED 2021 es un televisor de gama media con una calidad de imagen impresionante, una plataforma inteligente fácil de usar y características adicionales como una buena conectividad y sonido envolvente. Es una excelente opción para aquellos que buscan un televisor de alta calidad a un precio razonable.',
    ],
    pros: [
      'Excelente calidad de imagen',
      'Buen sistema de iluminación',
      'Buena conectividad',
      'Plataforma inteligente fácil de usar',
      'Buen sonido envolvente',
    ],
    con: [
      'Diseño minimalista podría ser simple',
      'Falta de soporte para algunos servicios',
      "Control remoto podría ser mejor",
    ],
    stars: 4.2,
    rating: 203,
    shortDesc: 'Hisense 50E76GQ es un televisor QLED de gama media de 50 pulgadas que ofrece una calidad de imagen decente con buena iluminación y colores vibrantes. Incluye la plataforma Android TV como sistema operativo y compatibilidad con Google Assistant. Sin embargo, su ángulo de visión es limitado y la calidad de sonido podría mejorarse.',
    price: '574',
    decimal: '99',
  },
  {
    id: uuidv4(),
    pos: 3,
    name: 'TCL 55P739',
    link: 'https://amzn.to/3StQ4ib',
    linkTitle: 'Ver en Amazon TCL 55P739',
    image: '/TCL_55P739.png',
    imageAlt: 'Imágen del televisor TCL 55P739',
    features: {
      panel: 'LED',
      size: '55″',
      resolution: '4K',
      os: 'VIDAA U5',
    },
    text: [
      'El TCL 55P739 es un Smart TV de 55 pulgadas que cuenta con una resolución 4K HDR y tecnología Ultra HD que brinda una calidad de imagen increíblemente clara y nítida. Además, incorpora la plataforma Google TV, la cual permite acceder a una gran cantidad de contenido, aplicaciones y juegos con una experiencia de navegación sencilla e intuitiva.',
      'Este televisor también cuenta con la tecnología Motion Clarity, la cual mejora la nitidez de la imagen en escenas de movimiento rápido, así como la función Game Master, diseñada para optimizar la experiencia de juego, reduciendo el tiempo de respuesta y minimizando la latencia.',
      'En cuanto a la calidad de audio, el TCL 55P739 viene equipado con Dolby Vision y Atmos, lo que proporciona una experiencia envolvente de sonido y una calidad de imagen impresionante. Además, cuenta con Google Assistant incorporado y es compatible con Alexa, lo que permite controlar fácilmente el televisor con comandos de voz y realizar búsquedas de contenido sin tener que levantar un dedo.',
      'En resumen, el TCL 55P739 es un Smart TV de alta gama que ofrece una combinación de características avanzadas en cuanto a calidad de imagen y sonido, así como una gran cantidad de opciones de entretenimiento gracias a la plataforma Google TV. Además, la capacidad de controlar el televisor con comandos de voz hace que sea una opción atractiva para aquellos que buscan una experiencia de visualización fácil e intuitiva.',
    ],
    pros: [
      'Excelente calidad de imagen',
      'Buen sistema de iluminación',
      'Buena conectividad',
      'Plataforma inteligente fácil de usar',
      'Buen sonido envolvente',
    ],
    con: [
      'Diseño minimalista podría ser simple',
      'Falta de soporte para algunos servicios',
      "Control remoto podría ser mejor",
    ],
    stars: 4.2,
    rating: 203,
    shortDesc: 'El TCL 55P739 es un Smart TV de 55" con resolución 4K HDR, Google TV, Dolby Vision y Atmos, Game Master y Google Assistant incorporado. Ofrece una calidad de imagen impresionante y una amplia gama de opciones de entretenimiento. También cuenta con funciones de juego optimizadas y es compatible con Alexa.',
    price: '574',
    decimal: '99',
  },
  {
    id: uuidv4(),
    pos: 2,
    name: 'Philips 65OLED855/12, OLED TV de 65" 4K',
    link: 'https://amzn.to/3ECmEsi',
    linkTitle: 'Ver en Amazon Philips 65OLED855/12, OLED TV de 65" 4K',
    image: '/TCL_55P739.png',
    imageAlt: 'Imágen del televisor Philips 65OLED855/12, OLED TV de 65" 4K',
    features: {
      panel: 'OLED',
      size: '65″',
      resolution: '4K',
      os: 'Android TV',
    },
    text: [
      'El Philips 65OLED855/12 es una impresionante televisión OLED de 65 pulgadas con resolución 4K. Esta TV ofrece imágenes vibrantes y nítidas gracias a la tecnología OLED, que permite mostrar negros profundos y colores brillantes con una alta precisión. Además, cuenta con tecnología de procesamiento de imágenes P5 de quinta generación que mejora la calidad de imagen de cualquier contenido, ya sea en resolución 4K, Full HD o incluso en baja resolución.',
      'El diseño del Philips 65OLED855/12 es elegante y minimalista, con un marco estrecho y un soporte de metal delgado que lo hacen lucir impresionante en cualquier sala de estar. La TV también viene equipada con una gran variedad de características para mejorar la experiencia del usuario, como el Ambilight de tres lados, que proyecta una luz suave detrás de la televisión para crear un ambiente envolvente que coincide con el contenido en pantalla.',
      'La tecnología Smart TV de Philips también está presente en el 65OLED855/12, lo que significa que los usuarios pueden acceder fácilmente a sus servicios de streaming favoritos, navegar por la web, y conectarse con otros dispositivos de forma rápida y sencilla. También incluye el asistente de voz de Google, que permite controlar la TV con comandos de voz, y la posibilidad de usar Alexa a través de dispositivos compatibles.',
      'En cuanto a conectividad, el Philips 65OLED855/12 cuenta con cuatro puertos HDMI, dos puertos USB y un puerto Ethernet, lo que significa que los usuarios pueden conectar una amplia variedad de dispositivos, como consolas de videojuegos, reproductores de Blu-ray, y dispositivos de almacenamiento. También cuenta con conectividad Bluetooth y WiFi para una fácil conectividad con dispositivos inalámbricos.',
      'En resumen, el Philips 65OLED855/12 es una impresionante televisión OLED de 65 pulgadas que ofrece una experiencia visual de alta calidad, una gran variedad de características inteligentes, y una conectividad completa con otros dispositivos. Si buscas una televisión premium que ofrezca una experiencia de visualización envolvente, esta TV es una excelente opción.',
    ],
    pros: [
      'Imágenes vibrantes y nítidas',
      'Tecnología de procesamiento de imágenes avanzada',
      'Diseño elegante y minimalista',
      'Ambilight de tres lados',
      'Características inteligentes completas',
    ],
    con: [
      'Precio alto',
      'Sonido mejorable',
    ],
    stars: 4.5,
    rating: 19,
    shortDesc: 'El Philips 65OLED855/12 es una impresionante televisión OLED de 65 pulgadas con resolución 4K y tecnología de procesamiento de imágenes avanzada. Además, cuenta con un diseño elegante y minimalista, características inteligentes completas y Ambilight de tres lados. El sonido podría ser mejor y su precio es alto.',
    price: '1.309',
    decimal: '00',
  },
  {
    id: uuidv4(),
    pos: 1,
    name: 'LG OLED42C26LB',
    link: 'https://amzn.to/3EzuqTQ',
    linkTitle: 'Ver en Amazon LG OLED42C26LB',
    image: '/lg_oled_evo.png',
    imageAlt: 'Imágen del televisor LG OLED42C26LB',
    features: {
      panel: 'OLED',
      size: '65″',
      resolution: '4K',
      os: 'WebOS',
    },
    text: [
      'El OLED42C26LB es un televisor de alta definición de 42 pulgadas que ofrece una calidad de imagen excepcional gracias a su resolución Ultra HD 4K y la tecnología OLED. Con una resolución cuatro veces mayor que la de un televisor Full HD convencional, este modelo permite disfrutar de una experiencia visual envolvente y de alta calidad.',
      'Además, este televisor cuenta con la función Smart TV, que te permite acceder a una amplia variedad de contenidos y servicios en línea directamente desde tu televisor, como aplicaciones de streaming, juegos, música y más. Todo esto es posible gracias al sistema operativo webOS de LG, que ofrece una interfaz intuitiva y fácil de usar para navegar por los diferentes servicios disponibles.',
      'La tecnología HDR (High Dynamic Range) del OLED42C26LB te ofrece una experiencia de visualización aún más impresionante, con colores más vibrantes y contrastes más intensos. Además, la tecnología OLED permite una visualización más nítida y detallada, incluso en escenas oscuras.',
      'En términos de conectividad, este televisor cuenta con varias opciones, incluyendo tres puertos HDMI, dos puertos USB, conexión Ethernet y Wi-Fi integrado, lo que permite una conexión rápida y sencilla a otros dispositivos y redes.',
      'En resumen, el OLED42C26LB es una excelente opción para aquellos que buscan una calidad de imagen excepcional, una amplia variedad de contenido en línea y una interfaz intuitiva y fácil de usar, todo en un paquete compacto y elegante. Con su tecnología OLED, resolución Ultra HD 4K y función Smart TV, este televisor es una inversión segura para cualquier hogar.',
    ],
    pros: [
      'Resolución Ultra HD 4K',
      'Tecnología OLED para colores intensos',
      'Función Smart TV con webOS',
      'Tecnología HDR para colores vibrantes',
      'Conectividad múltiple para dispositivos',
    ],
    con: [
      'Precio elevado',
      "Tamaño reducido de pantalla (42'')",
      'No compatible con algunos formatos',
      'Ángulos de visión limitados',
      'Altavoces internos de calidad media',
    ],
    stars: 4.5,
    rating: 8,
    shortDesc: 'El OLED42C26LB es un televisor de 42 pulgadas con resolución Ultra HD 4K y tecnología OLED que ofrece colores intensos y contrastes vibrantes. Cuenta con función Smart TV y sistema operativo webOS, así como tecnología HDR para una experiencia de visualización impresionante. Tiene múltiples opciones de conectividad, pero puede resultar costoso y tiene altavoces de calidad media.',
    price: '1.294',
    decimal: '29',
  },
]