import { v4 as uuidv4 } from 'uuid';

export const tvList = [
  {
    id: uuidv4(),
    pos: 10,
    name: 'Xiaomi P1E Smart TV 32',
    link: 'https://amzn.to/3EBkUzL',
    linkTitle: 'Ver en Amazon Xiaomi P1E Smart TV 32',
    image: '/xiaomi_p1e.png',
    imageAlt: 'Imágen del televisor Xiaomi P1E Smart TV 32',
    features: {
      panel: 'LED',
      size: '32″',
      resolution: '1.366 x 768 pixeles (HD-ready / 720p)',
      os: 'Android TV 11.0',
    },
    text: [
      'El <strong>Xiaomi P1E Smart TV 32</strong> es un <strong>televisor inteligente</strong> con pantalla de <strong>32 pulgadas</strong> que ofrece una excelente <strong>calidad de imagen y sonido</strong>. La resolución de la pantalla es de 1366 x 768 píxeles y cuenta con tecnología LED para una mejor visualización de colores y contraste. Además, este televisor cuenta con <strong>conectividad Wi-Fi y Bluetooth</strong>, lo que permite una fácil conexión con otros dispositivos y la transmisión de contenido en línea.',
      'El Xiaomi P1E Smart TV 32 utiliza el sistema operativo <strong>Android TV 9.0</strong>, lo que significa que los usuarios tienen acceso a una amplia variedad de aplicaciones y servicios en línea, incluyendo Google Play Store, Netflix, Amazon Prime Video, y más. También cuenta con un procesador Quad-core, 1 GB de RAM y 8 GB de almacenamiento interno, lo que permite una experiencia de navegación fluida y rápida.',
      'En términos de conectividad, el Xiaomi P1E Smart TV 32 ofrece varias opciones, incluyendo tres puertos HDMI, dos puertos USB, entrada de audio y video, entrada LAN y salida de audio óptica. Además, cuenta con <strong>altavoces integrados de 10 W</strong> para una experiencia de audio inmersiva.',
      'En cuanto al diseño, el Xiaomi P1E Smart TV 32 tiene un aspecto moderno y elegante, con un marco delgado y un <strong>soporte en forma de U</strong>. Además, se puede montar en la pared para ahorrar espacio y mejorar la visualización.',
      'En conclusión, el Xiaomi P1E Smart TV 32 es una excelente opción para aquellos que buscan un televisor inteligente de alta calidad a un precio asequible. Con su pantalla de 32 pulgadas, resolución de 1366 x 768 píxeles, <strong>conectividad Wi-Fi y Bluetooth</strong>, sistema operativo <strong>Android TV 9.0</strong> y una variedad de opciones de conectividad, este televisor ofrece una experiencia de entretenimiento de alta calidad en cualquier momento y lugar.',
    ],
    pros: [
      'Pantalla de alta calidad.',
      'Acceso a aplicaciones en línea.',
      'Audio claro y nítido.',
      'Buen precio.',
      'Diseño elegante.',
    ],
    con: [
      'Resolución limitada.',
      'Tasa de refresco baja.',
    ],
    stars: 4,
    rating: 103,
    shortDesc: 'El Xiaomi P1E Smart TV de 32 pulgadas es una televisión inteligente de alta calidad y asequible. Cuenta con una pantalla LED de 1366 x 768 píxeles, acceso a una amplia variedad de aplicaciones y contenido en línea, audio claro y nítido, y un diseño elegante. Sin embargo, la resolución y la tasa de refresco son limitadas.',
    price: 199,
    decimal: 90,
  },
  {
    id: uuidv4(),
    pos: 9,
    name: 'LG Televisor 50UQ75006LF',
    link: 'https://amzn.to/3ISfjaT',
    linkTitle: 'Ver en Amazon LG Televisor 50UQ75006LF',
    image: '/LG_Televisor_50UQ75006LF.png',
    imageAlt: 'Imágen del televisor LG Televisor 50UQ75006LF',
    features: {
      panel: 'LCD tipo IPS',
      size: '50″',
      resolution: '4K UHD',
      os: 'webOS 6.0',
    },
    text: [
      'El <strong>LG Televisor 50UQ75006LF</strong> es un televisor inteligente de alta gama con pantalla de <strong>50 pulgadas</strong>, que ofrece una calidad de imagen excepcional gracias a su resolución 4K UHD (3840 x 2160 píxeles) y tecnología NanoCell que brinda una reproducción de color precisa y detallada. Además, cuenta con una tasa de refresco de 50Hz y una respuesta de tiempo de 5ms, lo que significa que los usuarios pueden disfrutar de imágenes suaves y fluidas sin retrasos ni distorsiones.',
      'El LG Televisor 50UQ75006LF también cuenta con <strong>conectividad Wi-Fi y Bluetooth</strong>, lo que permite una fácil conexión con otros dispositivos y la transmisión de contenido en línea. Además, es compatible con el asistente de voz Google Assistant y Amazon Alexa, lo que significa que los usuarios pueden controlar el televisor con comandos de voz.',
      'En términos de audio, el LG Televisor 50UQ75006LF cuenta con <strong>altavoces integrados de 20W</strong> que ofrecen una experiencia de audio envolvente y dinámica. También cuenta con la tecnología AI Sound, que analiza y optimiza automáticamente el audio en función del contenido que se está reproduciendo.',
      'En cuanto a su diseño, el LG Televisor 50UQ75006LF cuenta con un aspecto moderno y elegante con un marco delgado y un soporte en forma de U. Además, cuenta con la capacidad de montarse en la pared para ahorrar espacio y mejorar la visualización.',
      'El LG Televisor 50UQ75006LF utiliza el sistema operativo <strong>webOS 6.0</strong>, lo que significa que los usuarios tienen acceso a una amplia variedad de aplicaciones y servicios en línea, incluyendo Netflix, Amazon Prime Video, Disney+, y más. También cuenta con un procesador Quad-core, 2 GB de RAM y 16 GB de almacenamiento interno, lo que permite una experiencia de navegación fluida y rápida.',
      'En cuanto a la conectividad, el LG Televisor 50UQ75006LF ofrece varias opciones, incluyendo cuatro puertos HDMI, dos puertos USB, entrada de audio y video, entrada LAN y salida de audio óptica.',
      'En conclusión, el LG Televisor 50UQ75006LF es una excelente opción para aquellos que buscan un televisor inteligente de alta gama con una calidad de imagen excepcional, conectividad avanzada, y una experiencia de audio envolvente. Con su pantalla de 50 pulgadas, resolución 4K UHD, tecnología NanoCell, <strong>conectividad Wi-Fi y Bluetooth</strong>, sistema operativo <strong>webOS 6.0</strong>, y una variedad de opciones de conectividad, este televisor ofrece una experiencia de entretenimiento de alta calidad en cualquier momento y lugar.',
    ],
    pros: [
      'Buena calidad de imagen.',
      'Sistema operativo fácil de usar.',
      'Ángulo de visión amplio.',
      'Amplia variedad de aplicaciones.',
    ],
    con: [
      'Precio elevado.',
      'Sonido mejorable.',
      'Poco contraste en escenas oscuras.',
      'Sin soporte Dolby Vision.',
    ],
    stars: 4.5,
    rating: 54,
    shortDesc: 'El LG Televisor 50UQ75006LF es un televisor inteligente de 50 pulgadas con resolución 4K y tecnología UHD. Cuenta con un sistema operativo inteligente LG ThinQ AI, conectividad Wi-Fi y Bluetooth, y una amplia variedad de aplicaciones de streaming. Su diseño elegante con marcos ultra delgados lo hacen una excelente opción para cualquier hogar.',
    price: '385',
    decimal: '78',
  },
  {
    id: uuidv4(),
    pos: 8,
    name: 'Sony Bravia XR 55A75K',
    link: 'https://amzn.to/3y8n1aJ',
    linkTitle: 'Ver en Amazon Sony Bravia XR 55A75K',
    image: '/Sony_Bravia_XR_A75K.png',
    imageAlt: 'Imágen del televisor Sony Bravia XR 55A75K',
    features: {
      panel: 'OLED',
      size: '55″',
      resolution: '4K',
      os: 'Android TV',
    },
    text: [
      'El televisor <strong>Sony BRAVIA XR 55A75K</strong> es un modelo <strong>OLED</strong> de 55 pulgadas con resolución <strong>4K</strong> y tecnología <strong>HDR</strong>. Este televisor de alta gama cuenta con una amplia gama de funciones y características que lo hacen ideal para aquellos que buscan una experiencia visual excepcional.',
      'La tecnología <strong>OLED</strong> del televisor <strong>Sony BRAVIA XR 55A75K</strong> significa que cada píxel en la pantalla puede iluminarse o apagarse de forma independiente, lo que resulta en negros más profundos y colores más vibrantes en comparación con los televisores <strong>LCD</strong> tradicionales. Además, la resolución <strong>4K</strong> significa que la imagen es cuatro veces más nítida que la de un televisor <strong>Full HD</strong>.',
      'La tecnología <strong>HDR</strong> del televisor <strong>Sony BRAVIA XR 55A75K</strong> permite una mayor relación de contraste y un rango dinámico más amplio, lo que significa que las imágenes pueden mostrar detalles más finos en áreas tanto brillantes como oscuras. También cuenta con un procesador <strong>XR</strong> de última generación que mejora la calidad de la imagen y el sonido.',
      'El televisor <strong>Sony BRAVIA XR 55A75K</strong> también cuenta con la tecnología <strong>Acoustic Surface Audio</strong>, que utiliza la propia pantalla del televisor como un altavoz, lo que significa que el sonido parece provenir directamente de la pantalla. Además, este televisor viene con tecnología de <strong>control de voz</strong> y es compatible con los asistentes virtuales más populares como <strong>Alexa</strong> y <strong>Google Assistant</strong>.',
      'En cuanto a <strong>conectividad</strong>, el televisor <strong>Sony BRAVIA XR 55A75K</strong> cuenta con cuatro puertos <strong>HDMI</strong> y tres puertos <strong>USB</strong>, lo que permite conectar una amplia variedad de dispositivos, como consolas de videojuegos, reproductores de <strong>Blu-ray</strong> y discos duros externos. También cuenta con conectividad <strong>Bluetooth</strong> y <strong>Wi-Fi</strong>, lo que permite la transmisión de contenido desde dispositivos móviles y otros dispositivos habilitados para Bluetooth.',
      'En resumen, el televisor <strong>Sony BRAVIA XR 55A75K</strong> es una excelente opción para aquellos que buscan una experiencia visual y auditiva excepcional. Con su tecnología <strong>OLED</strong>, resolución <strong>4K</strong>, <strong>HDR</strong> y procesador <strong>XR</strong>, este televisor ofrece imágenes nítidas y realistas con una amplia gama de colores. Además, la tecnología <strong>Acoustic Surface Audio</strong>, la conectividad y la compatibilidad con asistentes virtuales lo hacen una opción ideal para aquellos que buscan lo último en tecnología de entretenimiento para el hogar.',
    ],
    pros: [
      'Excelente calidad de imagen',
      'Tecnología Acoustic Surface Audio',
      'Amplia conectividad',
      'Compatible con asistentes virtuales',
    ],
    con: [
      'Precio elevado',
      'No es compatible con HDR10+',
      'El control remoto puede ser complicado',
      'No cuenta con soporte de Dolby Atmos',
    ],
    stars: 4.5,
    rating: 125,
    shortDesc: 'El televisor Sony BRAVIA XR 55A75K cuenta con un panel OLED de 55 pulgadas, resolución 4K y tecnología HDR, brindando una excelente calidad de imagen. Además, tiene una amplia conectividad y es compatible con asistentes virtuales. Su precio elevado y la falta de soporte para HDR10+ y Dolby Atmos son sus principales desventajas.',
    price: '1.499',
    decimal: '00',
  },
  {
    id: uuidv4(),
    pos: 7,
    name: 'Sony XR90J',
    link: 'https://amzn.to/3XSluQo',
    linkTitle: 'Ver en Amazon Sony XR90J',
    image: '/Sony_TV_55_XR55X90J.png',
    imageAlt: 'Imágen del televisor Sony XR90J',
    features: {
      panel: 'LED',
      size: '55″',
      resolution: '4K UHD',
      os: 'Android TV',
    },
    text: [
      'El televisor <strong>Sony TV 55 XR55X90J UHD</strong> es un modelo de alta gama que ofrece una experiencia visual excepcional. Con una pantalla de <strong>55 pulgadas</strong> y resolución <strong>UHD</strong>, este televisor es compatible con tecnología <strong>HDR</strong> y cuenta con un potente procesador <strong>X1</strong>. También tiene altavoces integrados con tecnología <strong>Acoustic Multi-Audio</strong> que brinda un sonido envolvente de alta calidad.',
      'Este televisor cuenta con el sistema operativo <strong>Android TV</strong>, lo que significa que es compatible con una amplia variedad de aplicaciones de streaming de video y música. También cuenta con un <strong>control de voz</strong> incorporado que permite al usuario controlar el televisor con comandos de voz simples. Además, el televisor Sony TV 55 XR55X90J UHD tiene una <strong>conectividad</strong> excepcional, con múltiples puertos HDMI y USB, así como Wi-Fi y Bluetooth integrados.',
      'En resumen, el televisor <strong>Sony TV 55 XR55X90J UHD</strong> es una excelente opción para aquellos que buscan una experiencia de visualización y sonido excepcional. Con una pantalla de alta calidad y tecnología HDR, este televisor ofrece una imagen vibrante y realista. Además, su compatibilidad con Android TV, su control de voz y su amplia conectividad lo hacen una excelente opción para aquellos que buscan una experiencia de entretenimiento de alta calidad.',
    ],
    pros: [
      'Excelente calidad de imagen',
      'Tecnología Acoustic Multi-Audio',
      'Conectividad excepcional',
      'Control de voz incorporado',
    ],
    con: [
      'Precio elevado',
      'Ángulo de visión limitado',
      'La pantalla es reflectante',
      'No tiene soporte Dolby Vision',
    ],
    stars: 4.5,
    rating: 12,
    shortDesc: 'El televisor Sony XR55X90J UHD TRIL STV XR F.ARRAY BRAVI es un producto de alta calidad de Sony Corporation, una multinacional japonesa que fabrica una amplia gama de productos electrónicos, desde televisores y equipos de sonido hasta cámaras digitales y juegos electrónicos.',
    price: '1.303',
    decimal: '93',
  },
  {
    id: uuidv4(),
    pos: 6,
    name: 'Samsung TV QLED 4K 2022 55Q64B',
    link: 'https://amzn.to/3IR5J7V',
    linkTitle: 'Ver en Amazon Samsung TV QLED 4K 2022 55Q64B',
    image: '/samsung_qled_55q64.png',
    imageAlt: 'Imágen del televisor Samsung TV QLED 4K 2022 55Q64B',
    features: {
      panel: 'VA Edge LED',
      size: '55″',
      resolution: '4K',
      os: 'Tizen 6.0',
    },
    text: [
      'Samsung destaca en la gama media con su oferta QLED, que se caracteriza por su elegante diseño y el buen rendimiento de su sistema operativo, sin sacrificar la calidad de imagen. Sin embargo, hay diferencias significativas entre las familias de televisores.',
      'La línea Q75 es especialmente atractiva en términos de calidad-precio, ya que a partir de esta familia todos los modelos cuentan con HDMI 2.1. Es el televisor más asequible de Samsung este año para los jugadores.',
      'Si tienes una consola de última generación, este televisor es ideal. Con HDMI 2.1, su modo automático de baja latencia, tasa de refresco variable, modo para juegos y AMD FreeSync, ofrece una experiencia completa para los jugadores. En cuanto a la calidad de imagen, es buena, especialmente considerando su tamaño. Aunque Samsung llama a su gama alta "QLED", en realidad utiliza paneles VA con diferentes sistemas de retroiluminación, en este caso, Edge LED.',
      'El alto rango dinámico hace que los detalles se aprecien mejor, especialmente en escenas oscuras como las de Juego de Tronos. Aunque este modelo implementa HDR10, HDR10+ y HLG, es inexplicable que por su precio no sea compatible con Dolby Vision. En cuanto a la navegación por aplicaciones como Netflix o Prime Video, el Tizen 6.0 es bastante fluido.',
      "El modelo analizado es de 55 pulgadas, aunque también está disponible en versiones de 65 y 75 pulgadas. Si buscas una experiencia más premium con una mejor reproducción de color y brillo, tendrás que pagar más. En general, Samsung ha logrado un producto equilibrado con este televisor sin aumentar demasiado su precio.",
    ],
    pros: [
      'Diseño estilizado premium',
      'Con las últimas tecnologías para jugar',
      'Buena relación calidad precio',
    ],
    con: [
      'No es compatible con Dolby Vision',
      'Brillo mejorable',
    ],
    stars: 4.5,
    rating: 156,
    shortDesc: 'Samsung 2022 55Q75B - Smart TV de 55" con Resolución 4K UHD, Procesador QLED 4K con IA, Quantum HDR10+, Wide Viewing Angle, Motion Xcelerator Turbo+, OTS Lite y Alexa Integrada.',
    price: '1.099',
    decimal: '00',
  },
  {
    id: uuidv4(),
    pos: 5,
    name: 'Samsung TV Crystal UHD 2022 50BU8000',
    link: 'https://amzn.to/3KB6WSb',
    linkTitle: 'Ver en Amazon Samsung TV Crystal UHD 2022 50BU8000',
    image: '/Samsung_Crystal_50BU8000.png',
    imageAlt: 'Imágen del televisor Samsung TV Crystal UHD 2022 50BU8000',
    features: {
      panel: 'VA Edge LED',
      size: '55″',
      resolution: '4K',
      os: 'Tizen 6.0',
    },
    text: [
      'La Samsung TV Crystal UHD 2022 50BU8000 es un televisor de gama media que cuenta con un panel LED de 50 pulgadas con resolución 4K UHD y tecnología de cristal. Esto permite una imagen nítida y clara con colores vibrantes y contrastes profundos.',
      'Este modelo también cuenta con el procesador Crystal 4K de Samsung, que optimiza la calidad de imagen y el rendimiento del televisor. Además, viene equipado con el sistema operativo Tizen de Samsung, que es rápido y fácil de usar para acceder a aplicaciones de streaming como Netflix, Amazon Prime Video, y Disney+.',
      'Otras características notables incluyen el soporte para HDR, lo que permite una mayor profundidad de color y detalles en escenas oscuras, y la tecnología de sonido envolvente que ofrece una experiencia de audio mejorada. Además, la conectividad es amplia, incluyendo cuatro puertos HDMI, dos puertos USB, Wi-Fi integrado y Bluetooth.',
      'En general, la Samsung TV Crystal UHD 2022 50BU8000 es una excelente opción para aquellos que buscan un televisor de alta calidad a un precio asequible, con una buena calidad de imagen y una amplia gama de características y funciones.',
    ],
    pros: [
      'Buena calidad de imagen',
      'Fácil de usar',
      'Diseño elegante',
      'Buena relación calidad-precio',
    ],
    con: [
      'Ángulos de visión limitados',
      'Sonido débil',
    ],
    stars: 4.5,
    rating: 1.691,
    shortDesc: 'Samsung TV Crystal UHD 2022 50BU8000 ofrece una resolución 4K UHD con tecnología de cristal para una imagen nítida y colores vibrantes. Cuenta con el procesador Crystal 4K y sistema operativo Tizen para una mejor calidad de imagen y experiencia de usuario. Soporte para HDR y conectividad amplia con cuatro puertos HDMI, dos puertos USB, Wi-Fi integrado y Bluetooth. Sin embargo, puede tener un ángulo de visión limitado y carecer de algunas características avanzadas de modelos de gama alta.',
    price: '479',
    decimal: '00',
  },
  {
    id: uuidv4(),
    pos: 4,
    name: 'Hisense 50E76GQ QLED 2021',
    link: 'https://amzn.to/41srceW',
    linkTitle: 'Ver en Amazon Hisense 50E76GQ QLED 2021',
    image: '/Hisense_50E76GQ_QLED_2021.png',
    imageAlt: 'Imágen del televisor Hisense 50E76GQ QLED 2021',
    features: {
      panel: 'QLED',
      size: '55″',
      resolution: '4K',
      os: 'VIDAA U5',
    },
    text: [
      'El Hisense 50E76GQ QLED 2021 es un televisor de gama media con una calidad de imagen impresionante. Este televisor de 50 pulgadas cuenta con una resolución de 4K Ultra HD y tecnología QLED, lo que garantiza una imagen brillante y vibrante con una gran precisión de color. Además, cuenta con un sistema de iluminación trasera Full Array Local Dimming (FALD) que mejora aún más la calidad de la imagen al proporcionar un mayor contraste y profundidad.',
      'El diseño del Hisense 50E76GQ es elegante y minimalista, con un marco delgado que maximiza la pantalla. El televisor también cuenta con una plataforma inteligente que permite acceder fácilmente a una amplia gama de aplicaciones y servicios de streaming como Netflix, Amazon Prime Video y YouTube, entre otros. Además, el control remoto es intuitivo y fácil de usar.',
      'El análisis de este televisor muestra que su rendimiento es impresionante en términos de calidad de imagen, pero también cuenta con características adicionales como una buena conectividad que incluye cuatro puertos HDMI, dos puertos USB y una conexión de red Ethernet. Además, el televisor cuenta con tecnología de sonido Dolby Atmos que proporciona un sonido envolvente y claro.',
      'En resumen, el Hisense 50E76GQ QLED 2021 es un televisor de gama media con una calidad de imagen impresionante, una plataforma inteligente fácil de usar y características adicionales como una buena conectividad y sonido envolvente. Es una excelente opción para aquellos que buscan un televisor de alta calidad a un precio razonable.',
    ],
    pros: [
      'Excelente calidad de imagen',
      'Buen sistema de iluminación',
      'Buena conectividad',
      'Plataforma inteligente fácil de usar',
      'Buen sonido envolvente',
    ],
    con: [
      'Diseño minimalista podría ser simple',
      'Falta de soporte para algunos servicios',
      "Control remoto podría ser mejor",
    ],
    stars: 4.2,
    rating: 203,
    shortDesc: 'Hisense 50E76GQ es un televisor QLED de gama media de 50 pulgadas que ofrece una calidad de imagen decente con buena iluminación y colores vibrantes. Incluye la plataforma Android TV como sistema operativo y compatibilidad con Google Assistant. Sin embargo, su ángulo de visión es limitado y la calidad de sonido podría mejorarse.',
    price: '574',
    decimal: '99',
  },
  {
    id: uuidv4(),
    pos: 3,
    name: 'TCL 55P739',
    link: 'https://amzn.to/3StQ4ib',
    linkTitle: 'Ver en Amazon TCL 55P739',
    image: '/TCL_55P739.png',
    imageAlt: 'Imágen del televisor TCL 55P739',
    features: {
      panel: 'LED',
      size: '55″',
      resolution: '4K',
      os: 'VIDAA U5',
    },
    text: [
      'El TCL 55P739 es un Smart TV de 55 pulgadas que cuenta con una resolución 4K HDR y tecnología Ultra HD que brinda una calidad de imagen increíblemente clara y nítida. Además, incorpora la plataforma Google TV, la cual permite acceder a una gran cantidad de contenido, aplicaciones y juegos con una experiencia de navegación sencilla e intuitiva.',
      'Este televisor también cuenta con la tecnología Motion Clarity, la cual mejora la nitidez de la imagen en escenas de movimiento rápido, así como la función Game Master, diseñada para optimizar la experiencia de juego, reduciendo el tiempo de respuesta y minimizando la latencia.',
      'En cuanto a la calidad de audio, el TCL 55P739 viene equipado con Dolby Vision y Atmos, lo que proporciona una experiencia envolvente de sonido y una calidad de imagen impresionante. Además, cuenta con Google Assistant incorporado y es compatible con Alexa, lo que permite controlar fácilmente el televisor con comandos de voz y realizar búsquedas de contenido sin tener que levantar un dedo.',
      'En resumen, el TCL 55P739 es un Smart TV de alta gama que ofrece una combinación de características avanzadas en cuanto a calidad de imagen y sonido, así como una gran cantidad de opciones de entretenimiento gracias a la plataforma Google TV. Además, la capacidad de controlar el televisor con comandos de voz hace que sea una opción atractiva para aquellos que buscan una experiencia de visualización fácil e intuitiva.',
    ],
    pros: [
      'Excelente calidad de imagen',
      'Buen sistema de iluminación',
      'Buena conectividad',
      'Plataforma inteligente fácil de usar',
      'Buen sonido envolvente',
    ],
    con: [
      'Diseño minimalista podría ser simple',
      'Falta de soporte para algunos servicios',
      "Control remoto podría ser mejor",
    ],
    stars: 4.2,
    rating: 203,
    shortDesc: 'El TCL 55P739 es un Smart TV de 55" con resolución 4K HDR, Google TV, Dolby Vision y Atmos, Game Master y Google Assistant incorporado. Ofrece una calidad de imagen impresionante y una amplia gama de opciones de entretenimiento. También cuenta con funciones de juego optimizadas y es compatible con Alexa.',
    price: '574',
    decimal: '99',
  },
  {
    id: uuidv4(),
    pos: 2,
    name: 'Philips 65OLED855/12, OLED TV de 65" 4K',
    link: 'https://amzn.to/3ECmEsi',
    linkTitle: 'Ver en Amazon Philips 65OLED855/12, OLED TV de 65" 4K',
    image: '/Philips_65OLED855.png',
    imageAlt: 'Imágen del televisor Philips 65OLED855/12, OLED TV de 65" 4K',
    features: {
      panel: 'OLED',
      size: '65″',
      resolution: '4K',
      os: 'Android TV',
    },
    text: [
      'El Philips 65OLED855/12 es una impresionante televisión OLED de 65 pulgadas con resolución 4K. Esta TV ofrece imágenes vibrantes y nítidas gracias a la tecnología OLED, que permite mostrar negros profundos y colores brillantes con una alta precisión. Además, cuenta con tecnología de procesamiento de imágenes P5 de quinta generación que mejora la calidad de imagen de cualquier contenido, ya sea en resolución 4K, Full HD o incluso en baja resolución.',
      'El diseño del Philips 65OLED855/12 es elegante y minimalista, con un marco estrecho y un soporte de metal delgado que lo hacen lucir impresionante en cualquier sala de estar. La TV también viene equipada con una gran variedad de características para mejorar la experiencia del usuario, como el Ambilight de tres lados, que proyecta una luz suave detrás de la televisión para crear un ambiente envolvente que coincide con el contenido en pantalla.',
      'La tecnología Smart TV de Philips también está presente en el 65OLED855/12, lo que significa que los usuarios pueden acceder fácilmente a sus servicios de streaming favoritos, navegar por la web, y conectarse con otros dispositivos de forma rápida y sencilla. También incluye el asistente de voz de Google, que permite controlar la TV con comandos de voz, y la posibilidad de usar Alexa a través de dispositivos compatibles.',
      'En cuanto a conectividad, el Philips 65OLED855/12 cuenta con cuatro puertos HDMI, dos puertos USB y un puerto Ethernet, lo que significa que los usuarios pueden conectar una amplia variedad de dispositivos, como consolas de videojuegos, reproductores de Blu-ray, y dispositivos de almacenamiento. También cuenta con conectividad Bluetooth y WiFi para una fácil conectividad con dispositivos inalámbricos.',
      'En resumen, el Philips 65OLED855/12 es una impresionante televisión OLED de 65 pulgadas que ofrece una experiencia visual de alta calidad, una gran variedad de características inteligentes, y una conectividad completa con otros dispositivos. Si buscas una televisión premium que ofrezca una experiencia de visualización envolvente, esta TV es una excelente opción.',
    ],
    pros: [
      'Imágenes vibrantes y nítidas',
      'Tecnología de procesamiento de imágenes avanzada',
      'Diseño elegante y minimalista',
      'Ambilight de tres lados',
      'Características inteligentes completas',
    ],
    con: [
      'Precio alto',
      'Sonido mejorable',
    ],
    stars: 4.5,
    rating: 19,
    shortDesc: 'El Philips 65OLED855/12 es una impresionante televisión OLED de 65 pulgadas con resolución 4K y tecnología de procesamiento de imágenes avanzada. Además, cuenta con un diseño elegante y minimalista, características inteligentes completas y Ambilight de tres lados. El sonido podría ser mejor y su precio es alto.',
    price: '1.309',
    decimal: '00',
  },
  {
    id: uuidv4(),
    pos: 1,
    name: 'LG OLED42C26LB',
    link: 'https://amzn.to/3EzuqTQ',
    linkTitle: 'Ver en Amazon LG OLED42C26LB',
    image: '/lg_oled_evo.png',
    imageAlt: 'Imágen del televisor LG OLED42C26LB',
    features: {
      panel: 'OLED',
      size: '65″',
      resolution: '4K',
      os: 'WebOS',
    },
    text: [
      'El OLED42C26LB es un televisor de alta definición de 42 pulgadas que ofrece una calidad de imagen excepcional gracias a su resolución Ultra HD 4K y la tecnología OLED. Con una resolución cuatro veces mayor que la de un televisor Full HD convencional, este modelo permite disfrutar de una experiencia visual envolvente y de alta calidad.',
      'Además, este televisor cuenta con la función Smart TV, que te permite acceder a una amplia variedad de contenidos y servicios en línea directamente desde tu televisor, como aplicaciones de streaming, juegos, música y más. Todo esto es posible gracias al sistema operativo webOS de LG, que ofrece una interfaz intuitiva y fácil de usar para navegar por los diferentes servicios disponibles.',
      'La tecnología HDR (High Dynamic Range) del OLED42C26LB te ofrece una experiencia de visualización aún más impresionante, con colores más vibrantes y contrastes más intensos. Además, la tecnología OLED permite una visualización más nítida y detallada, incluso en escenas oscuras.',
      'En términos de conectividad, este televisor cuenta con varias opciones, incluyendo tres puertos HDMI, dos puertos USB, conexión Ethernet y Wi-Fi integrado, lo que permite una conexión rápida y sencilla a otros dispositivos y redes.',
      'En resumen, el OLED42C26LB es una excelente opción para aquellos que buscan una calidad de imagen excepcional, una amplia variedad de contenido en línea y una interfaz intuitiva y fácil de usar, todo en un paquete compacto y elegante. Con su tecnología OLED, resolución Ultra HD 4K y función Smart TV, este televisor es una inversión segura para cualquier hogar.',
    ],
    pros: [
      'Resolución Ultra HD 4K',
      'Tecnología OLED para colores intensos',
      'Función Smart TV con webOS',
      'Tecnología HDR para colores vibrantes',
      'Conectividad múltiple para dispositivos',
    ],
    con: [
      'Precio elevado',
      "Tamaño reducido de pantalla (42'')",
      'No compatible con algunos formatos',
      'Ángulos de visión limitados',
      'Altavoces internos de calidad media',
    ],
    stars: 4.5,
    rating: 8,
    shortDesc: 'El OLED42C26LB es un televisor de 42 pulgadas con resolución Ultra HD 4K y tecnología OLED que ofrece colores intensos y contrastes vibrantes. Cuenta con función Smart TV y sistema operativo webOS, así como tecnología HDR para una experiencia de visualización impresionante. Tiene múltiples opciones de conectividad, pero puede resultar costoso y tiene altavoces de calidad media.',
    price: '1.294',
    decimal: '29',
  },
]